### ISSUE TITLE
4D vector field

### ISSUE THREAD

**Issue by tbaudier** [open-vv/vv#46]
Open a 4D image.
Overlay a 4D vector field.

It fails:
Error while reading vf_midp_4D.mhd 
itk::MemoryAllocationError (0x7fc9f0000940)
Location: "TElement* itk::ImportImageContainer<TElementIdentifier, TElement>::AllocateElements(itk::ImportImageContainer<TElementIdentifier, TElement>::ElementIdentifier, bool) const [with TElementIdentifier = long unsigned int; TElement = itk::Vector<float, 3u>; itk::ImportImageContainer<TElementIdentifier, TElement>::ElementIdentifier = long unsigned int]" 
File: /usr/local/include/ITK-4.9/itkImportImageContainer.hxx
Line: 199
Description: Failed to allocate memory for image.

**Comment by djboersma** [comment]
The error message says that it cannot get enough RAM to do this. How much RAM do you have on available your machine? Are there any other programs running that use a lot of RAM (e.g. web browser)? What size is the vector field (dimx * dimy * dimz), how many phases or time steps?

**Comment by tbaudier** [comment]
Exactly, I didn't check the memory consumption.
Thank you
Thomas
