### ISSUE TITLE
Warnings with VTK 8

### ISSUE THREAD

**Issue by SimonRit** [open-vv/vv#52]
Warnings keep repeating on the standard output when VV is compiled with VTK 8. Here is an excerpt of the standard output:

Generic Warning: In /home/srit/src/vtk/vtk7/Common/ExecutionModel/vtkAlgorithm.cxx, line 1808
vtkAlgorithm::SetUpdateExtent was deprecated for VTK 7.1 and will be removed in a future version.

Generic Warning: In /home/srit/src/vtk/vtk7/Common/ExecutionModel/vtkAlgorithm.cxx, line 1796
vtkAlgorithm::SetUpdateExtent was deprecated for VTK 7.1 and will be removed in a future version.

Generic Warning: In /home/srit/src/vtk/vtk7/Common/ExecutionModel/vtkStreamingDemandDrivenPipeline.cxx, line 1531
vtkStreamingDemandDrivenPipeline::SetUpdateExtent was deprecated for VTK 7.1 and will be removed in a future version.

**Comment by tbaudier** [comment]
done with commit:
https://github.com/open-vv/vv/commit/d1dc57c5af88ff53c75904b1dd55722f9631a21e
