### ISSUE TITLE
Remove Module_ITKReview dependency

### ISSUE THREAD

**Issue by SimonRit** [open-vv/vv#56]
It seems that there is only one reason for having a dependency to Module_ITKReview is the use of itkLabelGeometryImageFilter.h in clitkBLUTDIR for getting the bounding box. I think it could be removed using itkLabelStatisticsImageFilter.h. To be checked but that would be nice.

**Comment by tbaudier** [comment]
I checked the value of the bounding box with both filters and it's the same. I commit the modification.

**Comment by SimonRit** [comment]
Great! Thanks a lot Thomas!
