### ISSUE TITLE
QVTKPaintEngine was deprecated for VTK 8.1 and will be removed in a future version

### ISSUE THREAD

**Issue by yurivict** [open-vv/vv#64]
Application prints this:
```
Generic Warning: In /usr/ports/math/vtk8/work/VTK-8.1.1/GUISupport/Qt/QVTKPaintEngine.cxx, line 25
QVTKPaintEngine was deprecated for VTK 8.1 and will be removed in a future version.
```
vtk8-8.1.1 on FreeBSD 11.2

**Comment by tbaudier** [comment]
Hi yurivict,

Thank you for your remark, I will need to use ```QVTKOpenGLNativeWidget```
https://www.vtk.org/doc/nightly/html/deprecated.html

**Comment by tbaudier** [comment]
Hi yurivict,

It's done with commit: 75719c377dd8aa759f32dd277cfd7b2f914ebfa8
