### ISSUE TITLE
Missing file clitkImageArithm_ggo.h

### ISSUE THREAD

**Issue by yurivict** [open-vv/vv#65]
It's included https://github.com/open-vv/vv/blob/master/tools/clitkImage2DicomDoseGenericFilter.h#L34 but isn't present in the repository.

**Comment by yurivict** [comment]
I also think that the whole text if registration/CMakeLists.txt should be excluded based on ```CLITK_BUILD_REGISTRATION```, not only a part of it.
With ```CLITK_BUILD_REGISTRATION=OFF```, it builds ```clitkAffineRegistrationLib``` but doesn't use it.

**Comment by tbaudier** [comment]
Hi yurivict,
I corrected the first problem with the commit: e751b47051ae80ecd388418ae39b388f15e627eb

**Comment by tbaudier** [comment]
And thank you for your second remark. It's done with commit: f2abd66846f46f61e6f16e339da46515525826b1

**Comment by yurivict** [comment]
Thank you, @tbaudier !
