### ISSUE TITLE
segfault with clitkDicomRTPlan2Gate

### ISSUE THREAD

**Issue by djboersma** [open-vv/vv#71]
It's me again. At MedAustron we have a "PDM" tool which creates artificial DICOM RT plans, for beam delivery studies. Trying to convert these to Gate plan files with the `clitkDicomRTPlan2Gate` tool results in a clean segfault. With `gdb` I found out that this happens during the loop starting in line 200 which retrieves the snout ID; however, this snout ID is actually never used! Commenting out this code (lines 200-206 in `tools/clitkDicomRTPlan2Gate.cxx` helps to make it work again for us. Since the snout ID is never ever used in the code, I think that this change is perfectly harmless for other uses/users.

The user who reported this to me says that this segfault is already pretty old, also with vv from at least one year ago it was impossible to use this clitk tool to convert those PDM-generated plan files into Gate format.

I don't see how the TPS pencil beam actor could in any way use the snout ID. This is dependent on device and clinic; for instance for the definition of passive elements such as a range shifter. I think it is better if the users define such passive elements themselves in the geometry definitions. So I think it would in any case be a natural thing to omit the snout completely from the code.

**Comment by tbaudier** [comment]
Hi,

You right, snoutId does not seem to be used at all.
I commented the lines with snoutID in commit https://github.com/open-vv/vv/commit/d55f025b18f68066a52b8f33c2dc6481e82c2580
I do not have DicomRTPlan to test it, can you do it please?

Thank you
Thomas

**Comment by djboersma** [comment]
Yep, no crash anymore! Thanks!
