### ISSUE TITLE
Typo in compilation instructions

### ISSUE THREAD

**Issue by alfredomp** [open-vv/vv#72]
There is a small typo in the compilation instructions in the website (https://www.creatis.insa-lyon.fr/rio/vv) in the compilation instructions of VV (section 3.5). The instruction:

**git clone https://github.com/open-vv/vv.git src**

should be replaced by:

**git clone https://github.com/open-vv/vv.git vv**

**Comment by tbaudier** [comment]
Hello,

I did the modification, thank you very much

Thomas
